server:
  port: 8090

spring:
  application:
    name:
  datasource:
    url: jdbc:h2:mem:bankdb
    username: sa
    password: ' '
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "classpath:application_qa.yml"
      - "classpath:application_prod.yml"
  profiles:
    active:
      - "qa"

management:
  metrics:
    enable:
      system: false

build:
  version: "3.0"

cards:
  message: "Welcome to MyBank Cards API Service"
  contactDetails:
    name: "Kousik Das"
    email: "kousik.das2223@gmail.com"
  supportNumbers:
    - 777-555-5555
    - 888-666-6666

