services:
  accounts_db:
    container_name: accountsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cards_db:
    container_name: cardsdb
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    extends:
      file: common-config.yml
      service: microservice-db-config

  loans_db:
    container_name: loansdb
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "daskous/springboot-api:s7-configserver"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health/readiness"]
      interval: 100s
      timeout: 5s
      retries: 4
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "daskous/springboot-api:s7-accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accounts_db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accounts_db/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "daskous/springboot-api:s7-cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cards_db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cards_db/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "daskous/springboot-api:s7-loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loans_db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loans_db/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  banknetwork:
    driver: "bridge"