services:
  network-deploy-service:
    networks:
      - banknetwork

  microservice-db-config:
    extends: network-deploy-service
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 1000m
    environment:
      JAVA_TOOL_OPTIONS:  "javaagent:/app/libs/opentelemetry-javaagent-2.13.1.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempor:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOG_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  microservice-eurekaserver-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
