services:
  accounts:
    image: "daskous/springboot-api:s4-accounts"
    environment:
      - BP_MEMORY_CALCULATOR=false
    ports:
      - "8081:8080"
    container_name: accounts
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 700M
        reservations:
          cpus: "0.1"
          memory: 700M
    networks:
      - banknetwork
  cards:
    image: "daskous/springboot-api:s4-cards"
    environment:
      - BP_MEMORY_CALCULATOR=false
    ports:
      - "9001:9000"
    container_name: cards
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 700M
        reservations:
          cpus: "0.1"
          memory: 700M
    networks:
      - banknetwork
  loans:
    image: "daskous/springboot-api:s4-loans"
    environment:
      - BP_MEMORY_CALCULATOR=false
    ports:
      - "8091:8090"
    container_name: loans
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 700M
        reservations:
          cpus: "0.1"
          memory: 700M
    networks:
      - banknetwork

networks:
  banknetwork:
    driver: bridge
