spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
    circuitbreaker:
      resilience4j:
        configs:
          default:
            sliding-window-size: 10
            failure-rate-threshold: 50
            wait-duration-in-open-state: 10000
            permitted-number-of-calls-in-half-open-state: 2
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
      
management:
  metrics:
    tags:
      enabled: true
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "My Bank Gateway Server Application"
    version: "1.0.0"

server:
  port: 8073

logging:
  level:
    com:
      springboottutorial:
        gatewayserver: DEBUG



